# Generated by Django 5.0.4 on 2024-04-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskName", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=1000)),
                ("modified", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
